#!/bin/bash
# Meepo Task Simulation Script
# Task: Create scripts directory and base hello.sh file

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  🤖 MEEPO TASK (Git-Backed)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  Task ID: meepo-83e3d87d"
echo "  Description: Create scripts directory and base hello.sh file"
echo "  Branch: feature/hello-world-1768043510277"
echo "  Mode: Simulated + Git Commit"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""


# ═══════════════════════════════════════════════════════════════
# Git Setup
# ═══════════════════════════════════════════════════════════════
echo "🔧 Setting up git..."

# Configure git
git config --global user.email "meepo@agent.local"
git config --global user.name "Meepo Agent"
git config --global init.defaultBranch main

# Setup SSH for git (keys mounted read-only, need writable copy)
mkdir -p /tmp/.ssh
chmod 700 /tmp/.ssh

# Copy SSH keys to writable location
if [ -f /root/.ssh/id_ed25519 ]; then
    cp /root/.ssh/id_ed25519 /tmp/.ssh/id_ed25519
    chmod 600 /tmp/.ssh/id_ed25519
    echo "Copied SSH key to /tmp/.ssh/"
elif [ -f /root/.ssh/id_rsa ]; then
    cp /root/.ssh/id_rsa /tmp/.ssh/id_rsa
    chmod 600 /tmp/.ssh/id_rsa
    echo "Copied SSH key to /tmp/.ssh/"
else
    echo "⚠️  No SSH key found - git push may fail"
fi

# Copy known_hosts if exists, or use pre-populated one from image
if [ -f /root/.ssh/known_hosts ]; then
    cp /root/.ssh/known_hosts /tmp/.ssh/known_hosts
else
    # The meepo-claude image has GitHub pre-added
    touch /tmp/.ssh/known_hosts
    ssh-keyscan github.com >> /tmp/.ssh/known_hosts 2>/dev/null
fi
chmod 600 /tmp/.ssh/known_hosts

# Configure git to use our writable SSH directory
export GIT_SSH_COMMAND="ssh -i /tmp/.ssh/id_ed25519 -o UserKnownHostsFile=/tmp/.ssh/known_hosts -o StrictHostKeyChecking=no"

cd /app

# Check if repo already cloned
if [ ! -d ".git" ]; then
    echo "📥 Cloning repository..."
    git clone git@github.com:EdbertChan/test-playground.git /tmp/repo
    if [ $? -ne 0 ]; then
        echo "❌ Clone failed! Check SSH key permissions and GitHub access."
        exit 1
    fi
    mv /tmp/repo/.git /app/.git
    rm -rf /tmp/repo
    git checkout -- . 2>/dev/null || true
fi

# Fetch and checkout/create branch
echo "🌿 Checking out branch: feature/hello-world-1768043510277"
git fetch origin || true

# Stash any local files (e.g. .meepo/ created by orchestrator)
git stash --include-untracked 2>/dev/null || true

# Try to checkout existing remote branch, or create new one
if git branch -r | grep -q "origin/feature/hello-world-1768043510277"; then
    echo "Branch exists on remote, checking out..."
    git checkout -B feature/hello-world-1768043510277 origin/feature/hello-world-1768043510277
else
    echo "Creating new branch..."
    git checkout -b feature/hello-world-1768043510277
fi

# Pull latest just in case
git pull origin feature/hello-world-1768043510277 --rebase 2>/dev/null || true

# Restore stashed files (overwriting with ours if conflict)
git stash pop 2>/dev/null || true

echo "Current commit: $(git log --oneline -1)"
echo "Current branch: $(git branch --show-current)"

echo ""


# ═══════════════════════════════════════════════════════════════
# Context from Previous Tasks
# ═══════════════════════════════════════════════════════════════
echo ""
echo "📚 Loading context from previous tasks..."

# Read parent task context if available
echo "  ℹ️  This is a root task (no parent)"

# Show recent git commits for context

echo ""
echo "  📜 Recent commits on branch:"
git log --oneline -5 2>/dev/null | sed 's/^/     /'


# Show existing task history
if [ -f "/app/.meepo/history.jsonl" ]; then
    echo ""
    echo "  📝 Task history (last 5 events):"
    tail -5 /app/.meepo/history.jsonl | while read line; do
        EVENT=$(echo "$line" | grep -o '"event":"[^"]*"' | cut -d'"' -f4)
        ID=$(echo "$line" | grep -o '"id":"[^"]*"' | cut -d'"' -f4)
        echo "     - $EVENT: $ID"
    done
fi

echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

sleep 1
echo "📋 Analyzing task requirements..."
echo "   Problem: No scripts directory or hello.sh file exists in the repository"
sleep 1
echo "🔍 Scanning workspace structure..."
sleep 1
echo "📝 Planning implementation approach..."
echo "   Approach: Create scripts/ directory and add executable hello.sh with shebang"
sleep 1
echo "💻 Writing code..."

# Create sample files (simulated code changes)
mkdir -p /app/src
cat > /app/src/meepo_83e3d87d.ts << 'CODEOF'
// Generated by Meepo AI Agent
// Task ID: meepo-83e3d87d
// Summary: Initialize scripts/ directory with empty hello.sh
// Problem: No scripts directory or hello.sh file exists in the repository
// Approach: Create scripts/ directory and add executable hello.sh with shebang

export const taskComplete = true;
export const taskId = "meepo-83e3d87d";
CODEOF

# Write task metadata to .meepo/tasks/
mkdir -p /app/.meepo/tasks
cat > /app/.meepo/tasks/meepo-83e3d87d.json << 'METAEOF'
{
  "id": "meepo-83e3d87d",
  "summary": "Initialize scripts/ directory with empty hello.sh",
  "problem": "No scripts directory or hello.sh file exists in the repository",
  "approach": "Create scripts/ directory and add executable hello.sh with shebang",
  "testPlan": "1. scripts/ directory exists\n2. scripts/hello.sh exists and is executable\n3. Running ./scripts/hello.sh produces no errors\n",
  "reproCommand": "ls -la scripts/ && bash scripts/hello.sh",
  "status": "completed",
  "branch": "feature/hello-world-1768043510277",
  "parentTask": null,
  "createdAt": "2026-01-10T11:11:50.282Z",
  "completedAt": "2026-01-10T11:11:50.282Z"
}
METAEOF

# Append to history log
echo '{"ts":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'","event":"task_completed","id":"meepo-83e3d87d","branch":"feature/hello-world-1768043510277"}' >> /app/.meepo/history.jsonl

sleep 1
echo "🔧 Running linter and fixing issues..."
sleep 1
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  📁 FILES CREATED:"
echo "════════════════════════════════════════════════════════════"
echo ""
ls -la /app/src/
echo ""
echo "  📋 Task Metadata: /app/.meepo/tasks/meepo-83e3d87d.json"
echo ""


# ═══════════════════════════════════════════════════════════════
# Git Commit & Push
# ═══════════════════════════════════════════════════════════════
echo "════════════════════════════════════════════════════════════"
echo "  📤 Git Commit & Push"
echo "════════════════════════════════════════════════════════════"
echo ""

cd /app
git add -A
git commit -m "[meepo] meepo-83e3d87d: Initialize scripts/ directory with empty hello.sh

Problem: No scripts directory or hello.sh file exists in the repository\n\nApproach: Create scripts/ directory and add executable hello.sh with shebang\n\nTest Plan:\n1. scripts/ directory exists
2. scripts/hello.sh exists and is executable
3. Running ./scripts/hello.sh produces no errors
\n\nRepro: ls -la scripts/ && bash scripts/hello.sh\n\nTask-ID: meepo-83e3d87d"

echo ""
echo "Pushing to origin/feature/hello-world-1768043510277..."
# Try normal push first, then force push if needed (for experiment rebases)
if ! git push origin feature/hello-world-1768043510277; then
    echo "Normal push failed, trying force push..."
    git push origin feature/hello-world-1768043510277 --force-with-lease || echo "⚠️  Push failed (check auth)"
fi
echo ""
echo "✅ Committed: $(git rev-parse --short HEAD)"
echo ""



echo "✅ SIMULATION: Task completed successfully!"
echo ""
sleep 2
exit 0

